# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Build FirstJob
  - job: SecondJob
    steps:
    - script: echo Build SecondJob
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo DevDeployJob
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - script: echo QADeployJob
- stage: ProdDeploy
  jobs:
    - job: ProdDeployJob
      steps:
      - script: echo ProdDeployJob


