# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo $(system.DefaultWorkingDirectory)
        echo in Build environment
    displayName: 'QA'
- stage: QA
  jobs:
  - job: QAJob
    steps:
    - script: echo Hello, world!
    displayName: 'Run a one-line script'
- stage: Prod
  jobs:
  - job: ProdJob
    dependsOn: QAJob
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
