# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(System.DefaultWorkingDirectory)
  displayName: 'System directory check'

# resources:
# - repo: self

# variables:
#   tag: '$(Build.BuildId)'

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#       - task: Docker@2
#         inputs:
#           containerRegistry: 'docker-connection'
#           repository: 'phillysrevenge/currency-exchange-devops'
#           command: 'buildAndPush'
#           Dockerfile: '**/Dockerfile'
#       - task: CopyFiles@2
#         inputs:
#           SourceFolder: '$(System.DefaultWorkingDirectory)'
#           Contents: '**/*.yaml'
#           TargetFolder: '$(Build.ArtifactStagingDirectory)'
#       - task: PublishBuildArtifacts@1
#         inputs:
#           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#           ArtifactName: 'manifests'
#           publishLocation: 'Container'
# - stage: Deploy
#   displayName: Deploy image
#   jobs:
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: DownloadPipelineArtifact@2
#       inputs:
#         buildType: 'current'
#         artifactName: 'manifests'
#         itemPattern: '**/*.yaml'
#         targetPath: '$(System.ArtifactsDirectory)'
#     - task: KubernetesManifest@1
#       inputs:
#         action: 'deploy'
#         connectionType: 'kubernetesServiceConnection'
#         namespace: 'default'
#         manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
#         containers: 'phillysrevenge/currency-exchange-devops:${tag}'